name: Check Jenkins pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  checking-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create Jenkins Home
        run: mkdir -p jenkinsHome

      - name: Run Jenkinsfile using jenkinsfile-runner
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v ${{ github.workspace }}/jenkinsHome:/jenkinsHome \
            jenkinsci/jenkinsfile-runner \
            --runHome /jenkinsHome \
            --file /workspace/Jenkinsfile

      - name: Check test result
        run: |
          if grep -q "Tests run: 4, Failures: 0" jenkinsHome/jobs/job/builds/1/log; then
            echo "Tests passed."
          else
            echo "Tests failed."
            exit 1
          fi

      - name: Check add Contacts
        run: |
          if grep -q "@Test checkAddContacts()" jenkinsHome/jobs/job/builds/1/log; then
            echo "checkAddContacts test exists."
          else
            echo "checkAddContacts test missing."
            exit 1
          fi
